insert into seminar (name,subject,status) values('数理物理学ゼミ',4,2);
insert into seminar (name,subject,status) values('流体力学ゼミ',6,3);
insert into seminar (name,subject,status) values('杉山相対性理論ゼミ',6,3);
insert into seminar (name,subject,status) values('松坂集合位相ゼミ',4,3);
insert into seminar (name,subject,status) values('院試演習勉強会',14,3);
insert into seminar (name,subject,status,day,start_time) values('Coqゼミ',4,1,"月曜日",'18:00');
insert into seminar (name,subject,status) values('古事記輪読会',1,3);
insert into seminar (name,subject,status,day,start_time,content) values('確率解析ゼミ',4,1,'木曜日','19:00','計算と例題で「なるほど」と分かる確率微分方程式]という本を読んで，確率解析について学びます．');
insert into seminar (name,subject,status,content) values('田崎統計力学ゼミ',6,3,'田崎統計力学をゆっくり読み進めています。現在は2巻の11章を読んでいます。形式は担当者が発表する形です。');
insert into seminar (name,subject,status) values('ディープラーニングゼミ','情報科学',3,);
insert into seminar (name,subject,status,day,start_time,content) values('気象学ゼミ',7,1,'土曜日','20:00','「一般気象学（小倉義光）_第2版補訂版」を講義形式で進めるもの。各回録画して、notion上で公開しています。');
insert into seminar (name,subject,status,day,start_time,content) values('堀田現代量子力学を読もうの会',6,1,'水曜日','22:00','堀田昌寛著「入門現代の量子力学」を読んでいき、量子力学や量子情報の基本的な知識について学んでいきます。');
insert into seminar (name,subject,status) values ('生物輪読ゼミ',10,3);
insert into seminar (name,subject,status) values ('数値計算',0,2);
insert into seminar (name,subject,status,day,start_time,content) values('音響工学原論',9,1,'日曜日','16:00','音響工学原論というpdfをみんなで読みます。');
